import { useMemo, useState } from 'react';

const EMOJI_DATA = [
  { e: '😀', k: 'grinning face smile happy' },
  { e: '😃', k: 'grinning face big eyes smile' },
  { e: '😄', k: 'grinning face smiling eyes smile' },
  { e: '😁', k: 'beaming face smiling eyes smile' },
  { e: '😆', k: 'grinning squinting face laugh' },
  { e: '😅', k: 'grinning sweat smile relief' },
  { e: '😂', k: 'face tears joy laugh crying' },
  { e: '🤣', k: 'rolling floor laughing' },
  { e: '😊', k: 'smiling face smiling eyes blush' },
  { e: '😇', k: 'smiling face halo angel innocent' },
  { e: '🙂', k: 'slightly smiling face' },
  { e: '🙃', k: 'upside down face silly' },
  { e: '😉', k: 'winking face wink' },
  { e: '😌', k: 'relieved face calm' },
  { e: '😍', k: 'smiling heart eyes love' },
  { e: '🥰', k: 'smiling hearts love crush' },
  { e: '😘', k: 'face blowing kiss love' },
  { e: '😗', k: 'kissing face kiss' },
  { e: '😙', k: 'kissing smiling eyes' },
  { e: '😚', k: 'kissing closed eyes' },
  { e: '😋', k: 'savoring food yummy face' },
  { e: '😛', k: 'face tongue sticking out' },
  { e: '😝', k: 'squinting tongue silly' },
  { e: '😜', k: 'winking tongue silly' },
  { e: '🤪', k: 'crazy face zany' },
  { e: '🤨', k: 'face raised eyebrow suspicious' },
  { e: '🧐', k: 'face monocle inspect' },
  { e: '🤓', k: 'nerd face glasses' },
  { e: '😎', k: 'smiling sunglasses cool' },
  { e: '🥸', k: 'disguised face fake nose' },
  { e: '🤩', k: 'star struck excited wow' },
  { e: '🥳', k: 'partying face celebration party' },
  { e: '😏', k: 'smirking face smirk' },
  { e: '😒', k: 'unamused face annoyed' },
  { e: '😞', k: 'disappointed face sad' },
  { e: '😔', k: 'pensive face sad thinking' },
  { e: '😟', k: 'worried face concern' },
  { e: '😕', k: 'confused face' },
  { e: '🙁', k: 'slightly frowning sad' },
  { e: '😣', k: 'persevering face struggle' },
  { e: '😖', k: 'confounded face frustrated' },
  { e: '😫', k: 'tired face exhausted' },
  { e: '😩', k: 'weary face tired sad' },
  { e: '🥺', k: 'pleading face puppy eyes' },
  { e: '😢', k: 'crying face tear sad' },
  { e: '😭', k: 'loudly crying face sob' },
  { e: '😤', k: 'face steam nose angry' },
  { e: '😠', k: 'angry face mad' },
  { e: '😡', k: 'pouting anger furious' },
  { e: '🤬', k: 'face symbols mouth curse' },
  { e: '🤯', k: 'exploding head mind blown' },
  { e: '😳', k: 'flushed face embarrassed' },
  { e: '🥵', k: 'hot face sweating heat' },
  { e: '🥶', k: 'cold face freezing ice' },
  { e: '😱', k: 'screaming fear shock scared' },
  { e: '😨', k: 'fearful face scared' },
  { e: '😰', k: 'anxious sweat nervous' },
  { e: '😥', k: 'sad relieved disappointed' },
  { e: '😓', k: 'downcast sweat tired' },
  { e: '🤗', k: 'hugging face hug' },
  { e: '🤔', k: 'thinking face hmm question' },
  { e: '🫡', k: 'saluting face salute' },
  { e: '🤭', k: 'face hand over mouth secret' },
  { e: '🤫', k: 'shushing face quiet shh' },
  { e: '🤥', k: 'lying face pinocchio' },
  { e: '😶', k: 'face without mouth silent' },
  { e: '😐', k: 'neutral face meh' },
  { e: '😑', k: 'expressionless face blank' },
  { e: '😬', k: 'grimacing face awkward' },
  { e: '🙄', k: 'face rolling eyes annoyed' },
  { e: '😯', k: 'hushed face surprised' },
  { e: '😦', k: 'frowning open mouth' },
  { e: '😧', k: 'anguished face distress' },
  { e: '😮', k: 'face open mouth surprised' },
  { e: '😲', k: 'astonished face amazed' },
  { e: '🥱', k: 'yawning face sleepy' },
  { e: '😴', k: 'sleeping face sleep' },
  { e: '🤤', k: 'drooling face hungry' },
  { e: '😪', k: 'sleepy face tired' },
  { e: '😵', k: 'dizzy face confused' },
  { e: '🤐', k: 'zipper mouth face quiet' },
  { e: '🥴', k: 'woozy face drunk' },
  { e: '🤢', k: 'nauseated face sick' },
  { e: '🤮', k: 'vomiting face sick puke' },
  { e: '🤧', k: 'sneezing face sneeze' },
  { e: '😷', k: 'face mask sick' },
  { e: '🤒', k: 'face thermometer fever sick' },
  { e: '🤕', k: 'face head bandage hurt' },
  { e: '🤑', k: 'money mouth face rich' },
  { e: '🤠', k: 'cowboy hat face' },
  { e: '😈', k: 'smiling horns devil evil' },
  { e: '👿', k: 'angry devil evil' },
  { e: '👹', k: 'ogre monster' },
  { e: '👺', k: 'goblin monster' },
  { e: '🤡', k: 'clown face' },
  { e: '💩', k: 'poop pile poo shit' },
  { e: '👻', k: 'ghost spooky' },
  { e: '💀', k: 'skull dead death' },
  { e: '👽', k: 'alien ufo' },
  { e: '👾', k: 'alien monster game' },
  { e: '🤖', k: 'robot machine' },
  { e: '🎃', k: 'jack-o-lantern halloween pumpkin' },
  { e: '😺', k: 'grinning cat smile' },
  { e: '😸', k: 'grinning cat smiling eyes' },
  { e: '😹', k: 'cat tears joy laugh' },
  { e: '😻', k: 'cat heart eyes love' },
  { e: '😼', k: 'cat wry smile smirk' },
  { e: '😽', k: 'kissing cat kiss' },
  { e: '🙀', k: 'weary cat scared' },
  { e: '😿', k: 'crying cat sad tear' },
  { e: '😾', k: 'pouting cat angry' },
  { e: '👋', k: 'waving hand bye hello' },
  { e: '🤚', k: 'raised back of hand' },
  { e: '🖐', k: 'hand with fingers splayed' },
  { e: '✋', k: 'raised hand stop' },
  { e: '🖖', k: 'vulcan salute star trek' },
  { e: '👌', k: 'ok hand perfect' },
  { e: '🤌', k: 'pinched fingers italian' },
  { e: '🤏', k: 'pinching hand small' },
  { e: '✌', k: 'victory hand peace' },
  { e: '🤞', k: 'crossed fingers luck' },
  { e: '🤟', k: 'love you gesture' },
  { e: '🤘', k: 'sign of horns rock metal' },
  { e: '🤙', k: 'call me hand' },
  { e: '👈', k: 'backhand index left point' },
  { e: '👉', k: 'backhand index right point' },
  { e: '👆', k: 'backhand index up point' },
  { e: '🖕', k: 'middle finger rude' },
  { e: '👇', k: 'backhand index down point' },
  { e: '☝', k: 'index pointing up' },
  { e: '👍', k: 'thumbs up like' },
  { e: '👎', k: 'thumbs down dislike' },
  { e: '✊', k: 'raised fist power' },
  { e: '👊', k: 'oncoming fist punch' },
  { e: '🤛', k: 'left facing fist' },
  { e: '🤜', k: 'right facing fist' },
  { e: '👏', k: 'clapping hands applause' },
  { e: '🙌', k: 'raising hands celebrate' },
  { e: '👐', k: 'open hands' },
  { e: '🤲', k: 'palms up together' },
  { e: '🤝', k: 'handshake deal' },
  { e: '🙏', k: 'folded hands pray please thanks' },
  { e: '✍', k: 'writing hand' },
  { e: '💅', k: 'nail polish nails' },
  { e: '🤳', k: 'selfie camera' },
  { e: '💪', k: 'flexed biceps muscle strong' },
  { e: '🦾', k: 'mechanical arm robot' },
  { e: '🦿', k: 'mechanical leg robot' },
  { e: '🦵', k: 'leg kick' },
  { e: '🦶', k: 'foot step' },
  { e: '👂', k: 'ear listen' },
  { e: '🦻', k: 'ear with hearing aid' },
  { e: '👃', k: 'nose smell' },
  { e: '🧠', k: 'brain mind' },
  { e: '🦷', k: 'tooth teeth' },
  { e: '👀', k: 'eyes look see' },
  { e: '👁', k: 'eye see' },
  { e: '👅', k: 'tongue taste' },
  { e: '👄', k: 'mouth lips' },
  { e: '💋', k: 'kiss mark lipstick' },
  { e: '🩸', k: 'drop blood' },
  { e: '💧', k: 'droplet water tear' },
  { e: '💦', k: 'sweat droplets water' },
  { e: '🩹', k: 'adhesive bandage' },
  { e: '🩺', k: 'stethoscope doctor' },
  { e: '🫀', k: 'anatomical heart' },
  { e: '🫁', k: 'lungs breathe' },
  { e: '🦴', k: 'bone skeleton' },
  { e: '👶', k: 'baby newborn' },
  { e: '👧', k: 'girl child' },
  { e: '🧒', k: 'child kid' },
  { e: '👦', k: 'boy child' },
  { e: '👩', k: 'woman lady' },
  { e: '🧑', k: 'person adult' },
  { e: '👨', k: 'man guy' },
  { e: '👩‍🦱', k: 'woman curly hair' },
  { e: '👨‍🦱', k: 'man curly hair' },
  { e: '👱‍♀️', k: 'woman blonde' },
  { e: '👱', k: 'person blonde' },
  { e: '👱‍♂️', k: 'man blonde' },
  { e: '🧔', k: 'beard person' },
  { e: '🧔‍♂️', k: 'man beard' },
  { e: '👩‍🦰', k: 'woman red hair' },
  { e: '👨‍🦰', k: 'man red hair' },
  { e: '👩‍🦳', k: 'woman white hair' },
  { e: '👨‍🦳', k: 'man white hair' },
  { e: '👩‍🦲', k: 'woman bald' },
  { e: '👨‍🦲', k: 'man bald' },
  { e: '🧕', k: 'woman headscarf hijab' },
  { e: '👵', k: 'old woman grandmother' },
  { e: '🧓', k: 'older person elderly' },
  { e: '👴', k: 'old man grandfather' },
  { e: '👲', k: 'man chinese cap' },
  { e: '👳', k: 'person turban' },
  { e: '👳‍♀️', k: 'woman turban' },
  { e: '👳‍♂️', k: 'man turban' },
  { e: '🧔‍♀️', k: 'woman beard' },
  { e: '🐶', k: 'dog face pet' },
  { e: '🐱', k: 'cat face pet' },
  { e: '🐭', k: 'mouse face rat' },
  { e: '🐹', k: 'hamster pet' },
  { e: '🐰', k: 'rabbit face bunny' },
  { e: '🦊', k: 'fox face' },
  { e: '🐻', k: 'bear face' },
  { e: '🐼', k: 'panda face' },
  { e: '🐨', k: 'koala bear' },
  { e: '🐯', k: 'tiger face' },
  { e: '🦁', k: 'lion face' },
  { e: '🐮', k: 'cow face' },
  { e: '🐷', k: 'pig face' },
  { e: '🐽', k: 'pig nose' },
  { e: '🐸', k: 'frog face' },
  { e: '🐵', k: 'monkey face' },
  { e: '🙈', k: 'see no evil monkey' },
  { e: '🙉', k: 'hear no evil monkey' },
  { e: '🙊', k: 'speak no evil monkey' },
  { e: '🐒', k: 'monkey animal' },
  { e: '🐔', k: 'chicken hen' },
  { e: '🐧', k: 'penguin bird' },
  { e: '🐦', k: 'bird' },
  { e: '🐤', k: 'baby chick' },
  { e: '🐣', k: 'hatching chick egg' },
  { e: '🐥', k: 'front facing baby chick' },
  { e: '🦆', k: 'duck bird' },
  { e: '🦅', k: 'eagle bird' },
  { e: '🦉', k: 'owl bird night' },
  { e: '🦇', k: 'bat vampire' },
  { e: '🐺', k: 'wolf animal' },
  { e: '🐗', k: 'boar wild pig' },
  { e: '🐴', k: 'horse face' },
  { e: '🦄', k: 'unicorn horse' },
  { e: '🐝', k: 'honeybee bee insect' },
  { e: '🪱', k: 'worm' },
  { e: '🐛', k: 'bug caterpillar' },
  { e: '🦋', k: 'butterfly insect' },
  { e: '🐌', k: 'snail slow' },
  { e: '🐞', k: 'lady beetle bug' },
  { e: '🐜', k: 'ant insect' },
  { e: '🪰', k: 'fly insect' },
  { e: '🪲', k: 'beetle insect' },
  { e: '🪳', k: 'cockroach bug' },
  { e: '🦟', k: 'mosquito insect' },
  { e: '🦗', k: 'cricket insect' },
  { e: '🕷', k: 'spider web' },
  { e: '🕸', k: 'spider web' },
  { e: '🦂', k: 'scorpion' },
  { e: '🐢', k: 'turtle tortoise' },
  { e: '🐍', k: 'snake reptile' },
  { e: '🦎', k: 'lizard reptile' },
  { e: '🦖', k: 't-rex dinosaur' },
  { e: '🦕', k: 'sauropod dinosaur' },
  { e: '🐙', k: 'octopus sea' },
  { e: '🦑', k: 'squid sea' },
  { e: '🦐', k: 'shrimp prawn' },
  { e: '🦞', k: 'lobster' },
  { e: '🦀', k: 'crab sea' },
  { e: '🐡', k: 'blowfish fish' },
  { e: '🐠', k: 'tropical fish' },
  { e: '🐟', k: 'fish sea' },
  { e: '🐬', k: 'dolphin sea' },
  { e: '🐳', k: 'spouting whale' },
  { e: '🐋', k: 'whale sea' },
  { e: '🦈', k: 'shark sea' },
  { e: '🐊', k: 'crocodile' },
  { e: '🐅', k: 'tiger animal' },
  { e: '🐆', k: 'leopard animal' },
  { e: '🦓', k: 'zebra animal' },
  { e: '🦍', k: 'gorilla animal' },
  { e: '🦧', k: 'orangutan ape' },
  { e: '🐘', k: 'elephant animal' },
  { e: '🦛', k: 'hippopotamus' },
  { e: '🦏', k: 'rhinoceros' },
  { e: '🐪', k: 'camel' },
  { e: '🐫', k: 'two hump camel' },
  { e: '🦒', k: 'giraffe animal' },
  { e: '🦘', k: 'kangaroo animal' },
  { e: '🦬', k: 'bison buffalo' },
  { e: '🍎', k: 'red apple fruit' },
  { e: '🍐', k: 'pear fruit' },
  { e: '🍊', k: 'tangerine orange fruit' },
  { e: '🍋', k: 'lemon fruit' },
  { e: '🍌', k: 'banana fruit' },
  { e: '🍉', k: 'watermelon fruit' },
  { e: '🍇', k: 'grapes fruit' },
  { e: '🍓', k: 'strawberry fruit' },
  { e: '🫐', k: 'blueberries fruit' },
  { e: '🍈', k: 'melon fruit' },
  { e: '🍒', k: 'cherries fruit' },
  { e: '🍑', k: 'peach fruit' },
  { e: '🥭', k: 'mango fruit' },
  { e: '🍍', k: 'pineapple fruit' },
  { e: '🥥', k: 'coconut fruit' },
  { e: '🥝', k: 'kiwi fruit' },
  { e: '🍅', k: 'tomato vegetable' },
  { e: '🍆', k: 'eggplant aubergine' },
  { e: '🥑', k: 'avocado fruit' },
  { e: '🥦', k: 'broccoli vegetable' },
  { e: '🥬', k: 'leafy green vegetable' },
  { e: '🥒', k: 'cucumber vegetable' },
  { e: '🌶', k: 'hot pepper chilli' },
  { e: '🫑', k: 'bell pepper' },
  { e: '🌽', k: 'corn maize' },
  { e: '🥕', k: 'carrot vegetable' },
  { e: '🧄', k: 'garlic' },
  { e: '🧅', k: 'onion' },
  { e: '🥔', k: 'potato vegetable' },
  { e: '🍠', k: 'roasted sweet potato' },
  { e: '🥐', k: 'croissant bread' },
  { e: '🥯', k: 'bagel bread' },
  { e: '🍞', k: 'bread loaf' },
  { e: '🥖', k: 'baguette bread' },
  { e: '🥨', k: 'pretzel' },
  { e: '🧀', k: 'cheese wedge' },
  { e: '🥚', k: 'egg food' },
  { e: '🍳', k: 'cooking fried egg pan' },
  { e: '🧈', k: 'butter' },
  { e: '🥞', k: 'pancakes breakfast' },
  { e: '🧇', k: 'waffle breakfast' },
  { e: '🥓', k: 'bacon meat' },
  { e: '🥩', k: 'cut of meat steak' },
  { e: '🍗', k: 'poultry leg chicken' },
  { e: '🍖', k: 'meat bone' },
  { e: '🌭', k: 'hot dog sausage' },
  { e: '🍔', k: 'hamburger burger' },
  { e: '🍟', k: 'french fries chips' },
  { e: '🍕', k: 'pizza food' },
  { e: '🥪', k: 'sandwich food' },
  { e: '🥙', k: 'stuffed flatbread wrap' },
  { e: '🧆', k: 'falafel food' },
  { e: '🌮', k: 'taco food' },
  { e: '🌯', k: 'burrito food' },
  { e: '🥗', k: 'green salad healthy' },
  { e: '🥘', k: 'shallow pan of food paella' },
  { e: '🫕', k: 'fondue cheese' },
  { e: '🍝', k: 'spaghetti pasta' },
  { e: '🍜', k: 'steaming bowl noodles' },
  { e: '🍲', k: 'pot of food stew' },
  { e: '🍛', k: 'curry rice' },
  { e: '🍣', k: 'sushi japanese' },
  { e: '🍱', k: 'bento box lunch' },
  { e: '🥟', k: 'dumpling food' },
  { e: '🦪', k: 'oyster seafood' },
  { e: '🍤', k: 'fried shrimp' },
  { e: '🍙', k: 'rice ball onigiri' },
  { e: '🍚', k: 'cooked rice' },
  { e: '🍘', k: 'rice cracker' },
  { e: '🍥', k: 'fish cake naruto' },
  { e: '🥠', k: 'fortune cookie' },
  { e: '🥮', k: 'moon cake' },
  { e: '🍢', k: 'oden skewer' },
  { e: '🍡', k: 'dango dumpling' },
  { e: '🍧', k: 'shaved ice dessert' },
  { e: '🍨', k: 'ice cream dessert' },
  { e: '🍦', k: 'soft ice cream' },
  { e: '🥧', k: 'pie dessert' },
  { e: '🧁', k: 'cupcake dessert' },
  { e: '🍰', k: 'shortcake cake' },
  { e: '🎂', k: 'birthday cake' },
  { e: '🍮', k: 'custard pudding' },
  { e: '🍭', k: 'lollipop candy' },
  { e: '🍬', k: 'candy sweet' },
  { e: '🍫', k: 'chocolate bar' },
  { e: '🍿', k: 'popcorn movie' },
  { e: '🍩', k: 'doughnut donut' },
  { e: '🍪', k: 'cookie biscuit' },
  { e: '🌰', k: 'chestnut' },
  { e: '🥜', k: 'peanuts nuts' },
  { e: '🍯', k: 'honey pot' },
  { e: '🥛', k: 'glass of milk' },
  { e: '🍼', k: 'baby bottle milk' },
  { e: '🫖', k: 'teapot tea' },
  { e: '☕', k: 'hot beverage coffee tea' },
  { e: '🍵', k: 'teacup tea green' },
  { e: '🧃', k: 'beverage box juice' },
  { e: '🥤', k: 'cup with straw drink' },
  { e: '🧋', k: 'bubble tea boba' },
  { e: '🍶', k: 'sake rice wine' },
  { e: '🍺', k: 'beer mug drink' },
  { e: '🍻', k: 'clinking beer cheers' },
  { e: '🥂', k: 'clinking glasses cheers toast' },
  { e: '🍷', k: 'wine glass drink' },
  { e: '🥃', k: 'tumbler glass whisky' },
  { e: '🍸', k: 'cocktail glass drink' },
  { e: '🍹', k: 'tropical drink' },
  { e: '🧉', k: 'mate tea' },
  { e: '🍾', k: 'bottle popping cork champagne' },
  { e: '🧊', k: 'ice cube cold' },
  { e: '🥄', k: 'spoon utensil' },
  { e: '🍴', k: 'fork and knife' },
  { e: '🍽', k: 'plate fork knife' },
  { e: '🥣', k: 'bowl with spoon' },
  { e: '🥡', k: 'takeout box food' },
  { e: '🥢', k: 'chopsticks' },
  { e: '🧂', k: 'salt' },
  { e: '⚽', k: 'soccer football ball' },
  { e: '🏀', k: 'basketball ball' },
  { e: '🏈', k: 'american football' },
  { e: '⚾', k: 'baseball ball' },
  { e: '🥎', k: 'softball ball' },
  { e: '🎾', k: 'tennis ball' },
  { e: '🏐', k: 'volleyball ball' },
  { e: '🏉', k: 'rugby ball' },
  { e: '🥏', k: 'flying disc frisbee' },
  { e: '🎱', k: 'pool 8 ball billiard' },
  { e: '🪀', k: 'yo-yo toy' },
  { e: '🏓', k: 'ping pong table tennis' },
  { e: '🏸', k: 'badminton shuttlecock' },
  { e: '🏒', k: 'ice hockey stick' },
  { e: '🏑', k: 'field hockey stick' },
  { e: '🥍', k: 'lacrosse stick' },
  { e: '🏏', k: 'cricket bat ball' },
  { e: '🪃', k: 'boomerang' },
  { e: '🥅', k: 'goal net' },
  { e: '⛳', k: 'flag in hole golf' },
  { e: '🪁', k: 'kite fly' },
  { e: '🏹', k: 'bow and arrow archery' },
  { e: '🎣', k: 'fishing pole fish' },
  { e: '🤿', k: 'diving mask scuba' },
  { e: '🥊', k: 'boxing glove' },
  { e: '🥋', k: 'martial arts uniform' },
  { e: '🎽', k: 'running shirt' },
  { e: '🛹', k: 'skateboard' },
  { e: '🛼', k: 'roller skate' },
  { e: '🛷', k: 'sled sleigh' },
  { e: '⛸', k: 'ice skate' },
  { e: '🥌', k: 'curling stone' },
  { e: '🎿', k: 'skis ski' },
  { e: '⛷', k: 'skier ski' },
  { e: '🏂', k: 'snowboarder' },
  { e: '🏋', k: 'weight lifter' },
  { e: '🏋️‍♂️', k: 'man weight lifting' },
  { e: '🤼', k: 'people wrestling' },
  { e: '🤸', k: 'person cartwheeling' },
  { e: '⛹', k: 'person bouncing ball' },
  { e: '🤺', k: 'person fencing sword' },
  { e: '🤾', k: 'person throwing handball' },
  { e: '🏌', k: 'person golfing' },
  { e: '🏇', k: 'horse racing' },
  { e: '🧘', k: 'person lotus position meditation' },
  { e: '🏄', k: 'person surfing' },
  { e: '🏊', k: 'person swimming' },
  { e: '🤽', k: 'person playing water polo' },
  { e: '🚣', k: 'person rowing boat' },
  { e: '🧗', k: 'person climbing' },
  { e: '🚵', k: 'person mountain biking' },
  { e: '🚴', k: 'person biking cycle' },
  { e: '🏆', k: 'trophy win champion' },
  { e: '🥇', k: 'gold medal first' },
  { e: '🥈', k: 'silver medal second' },
  { e: '🥉', k: 'bronze medal third' },
  { e: '🏅', k: 'sports medal' },
  { e: '🎖', k: 'military medal award' },
  { e: '🏵', k: 'rosette award' },
  { e: '🎗', k: 'reminder ribbon' },
  { e: '🎫', k: 'ticket event' },
  { e: '🎟', k: 'admission tickets event' },
  { e: '🎪', k: 'circus tent' },
  { e: '🤹', k: 'person juggling' },
  { e: '🎭', k: 'performing arts theater' },
  { e: '🩰', k: 'ballet shoes dance' },
  { e: '🎨', k: 'artist palette paint' },
  { e: '🎬', k: 'clapper board movie film' },
  { e: '🎤', k: 'microphone sing' },
  { e: '🎧', k: 'headphone music listen' },
  { e: '🎼', k: 'musical score' },
  { e: '🎹', k: 'musical keyboard piano' },
  { e: '🥁', k: 'drum percussion' },
  { e: '🪘', k: 'long drum' },
  { e: '🎷', k: 'saxophone jazz' },
  { e: '🎺', k: 'trumpet horn' },
  { e: '🪗', k: 'accordion music' },
  { e: '🎸', k: 'guitar rock' },
  { e: '🪕', k: 'banjo music' },
  { e: '🎻', k: 'violin strings' },
  { e: '🪈', k: 'flute music' },
  { e: '🎲', k: 'game die dice' },
  { e: '♟', k: 'chess pawn game' },
  { e: '🎯', k: 'direct hit target dart' },
  { e: '🎳', k: 'bowling game' },
  { e: '🎮', k: 'video game controller' },
  { e: '🎰', k: 'slot machine casino' },
  { e: '🧩', k: 'puzzle piece' },
  { e: '🚗', k: 'car automobile' },
  { e: '🚕', k: 'taxi cab' },
  { e: '🚙', k: 'suv recreational vehicle' },
  { e: '🚌', k: 'bus vehicle' },
  { e: '🚎', k: 'trolleybus tram' },
  { e: '🏎', k: 'racing car f1' },
  { e: '🚓', k: 'police car' },
  { e: '🚑', k: 'ambulance emergency' },
  { e: '🚒', k: 'fire engine firetruck' },
  { e: '🚐', k: 'minibus van' },
  { e: '🛻', k: 'pickup truck' },
  { e: '🚚', k: 'delivery truck' },
  { e: '🚛', k: 'articulated lorry truck' },
  { e: '🚜', k: 'tractor farm' },
  { e: '🦯', k: 'white cane blind' },
  { e: '🦽', k: 'manual wheelchair' },
  { e: '🦼', k: 'motorized wheelchair' },
  { e: '🛴', k: 'kick scooter' },
  { e: '🚲', k: 'bicycle bike' },
  { e: '🛵', k: 'motor scooter' },
  { e: '🏍', k: 'motorcycle bike' },
  { e: '🛺', k: 'auto rickshaw tuk tuk' },
  { e: '🚨', k: 'police car light siren' },
  { e: '🚔', k: 'oncoming police car' },
  { e: '🚍', k: 'oncoming bus' },
  { e: '🚘', k: 'oncoming automobile' },
  { e: '🚖', k: 'oncoming taxi' },
  { e: '🚡', k: 'aerial tramway cable car' },
  { e: '🚠', k: 'mountain cableway' },
  { e: '🚟', k: 'suspension railway' },
  { e: '🚃', k: 'railway car train' },
  { e: '🚋', k: 'tram car' },
  { e: '🚞', k: 'mountain railway' },
  { e: '🚝', k: 'monorail train' },
  { e: '🚄', k: 'high speed train' },
  { e: '🚅', k: 'bullet train' },
  { e: '🚈', k: 'light rail train' },
  { e: '🚂', k: 'locomotive steam train' },
  { e: '🚆', k: 'train railway' },
  { e: '🚇', k: 'metro subway' },
  { e: '🚊', k: 'tram stop' },
  { e: '🚉', k: 'station train' },
  { e: '✈', k: 'airplane plane flight' },
  { e: '🛫', k: 'airplane departure takeoff' },
  { e: '🛬', k: 'airplane arrival landing' },
  { e: '🛩', k: 'small airplane' },
  { e: '💺', k: 'seat chair' },
  { e: '🛰', k: 'satellite space' },
  { e: '🚀', k: 'rocket space launch' },
  { e: '🛸', k: 'flying saucer ufo' },
  { e: '🚁', k: 'helicopter' },
  { e: '🛶', k: 'canoe boat' },
  { e: '⛵', k: 'sailboat boat' },
  { e: '🚤', k: 'speedboat boat' },
  { e: '🛥', k: 'motor boat' },
  { e: '🛳', k: 'passenger ship cruise' },
  { e: '⛴', k: 'ferry boat' },
  { e: '🚢', k: 'ship boat' },
  { e: '⚓', k: 'anchor sea' },
  { e: '🪝', k: 'hook fishing' },
  { e: '⛽', k: 'fuel pump gas station' },
  { e: '🚧', k: 'construction barrier' },
  { e: '🚦', k: 'vertical traffic light' },
  { e: '🚥', k: 'horizontal traffic light' },
  { e: '🚏', k: 'bus stop' },
  { e: '🗺', k: 'world map travel' },
  { e: '🗿', k: 'moai statue easter island' },
  { e: '🗽', k: 'statue of liberty new york' },
  { e: '🗼', k: 'tokyo tower' },
  { e: '🏰', k: 'castle palace' },
  { e: '🏯', k: 'japanese castle' },
  { e: '🏟', k: 'stadium sports' },
  { e: '🎡', k: 'ferris wheel amusement' },
  { e: '🎢', k: 'roller coaster amusement' },
  { e: '🎠', k: 'carousel horse' },
  { e: '⛲', k: 'fountain water' },
  { e: '⛱', k: 'umbrella on ground beach' },
  { e: '🏖', k: 'beach with umbrella' },
  { e: '🏝', k: 'desert island' },
  { e: '🏜', k: 'desert sand' },
  { e: '🌋', k: 'volcano eruption' },
  { e: '⛰', k: 'mountain peak' },
  { e: '🏔', k: 'snow capped mountain' },
  { e: '🗻', k: 'mount fuji japan' },
  { e: '🏕', k: 'camping tent' },
  { e: '⛺', k: 'tent camp' },
  { e: '🛖', k: 'hut house' },
  { e: '🏘', k: 'houses buildings' },
  { e: '🏡', k: 'house garden home' },
  { e: '🏠', k: 'house home' },
  { e: '🏗', k: 'building construction crane' },
  { e: '🏭', k: 'factory industry' },
  { e: '🏢', k: 'office building' },
  { e: '🏬', k: 'department store' },
  { e: '🏣', k: 'japanese post office' },
  { e: '🏤', k: 'post office mail' },
  { e: '🏥', k: 'hospital medical' },
  { e: '🏦', k: 'bank money' },
  { e: '🏨', k: 'hotel stay' },
  { e: '🏪', k: 'convenience store' },
  { e: '🏫', k: 'school education' },
  { e: '🏩', k: 'love hotel' },
  { e: '💒', k: 'wedding chapel marriage' },
  { e: '🏛', k: 'classical building' },
  { e: '⛪', k: 'church worship' },
  { e: '🕌', k: 'mosque islam' },
  { e: '🕍', k: 'synagogue jewish' },
  { e: '🛕', k: 'hindu temple' },
  { e: '🕋', k: 'kaaba mecca' },
  { e: '⛩', k: 'shinto shrine' },
  { e: '🛤', k: 'railway track' },
  { e: '🛣', k: 'motorway highway' },
  { e: '🗾', k: 'map of japan' },
  { e: '🎑', k: 'moon viewing scenery' },
  { e: '🏞', k: 'national park' },
  { e: '🌅', k: 'sunrise morning' },
  { e: '🌄', k: 'sunrise over mountains' },
  { e: '🌠', k: 'shooting star night' },
  { e: '🎇', k: 'sparkler fireworks' },
  { e: '🎆', k: 'fireworks celebration' },
  { e: '🌇', k: 'sunset city evening' },
  { e: '🌆', k: 'cityscape dusk evening' },
  { e: '🏙', k: 'cityscape city buildings' },
  { e: '🌃', k: 'night with stars' },
  { e: '🌌', k: 'milky way galaxy' },
  { e: '🌉', k: 'bridge at night' },
  { e: '🌁', k: 'foggy fog' },
  { e: '⌚', k: 'watch time' },
  { e: '📱', k: 'mobile phone smartphone' },
  { e: '📲', k: 'mobile phone arrow incoming' },
  { e: '💻', k: 'laptop computer' },
  { e: '⌨', k: 'keyboard type' },
  { e: '🖥', k: 'desktop computer' },
  { e: '🖨', k: 'printer print' },
  { e: '🖱', k: 'computer mouse' },
  { e: '🖲', k: 'trackball mouse' },
  { e: '🕹', k: 'joystick game' },
  { e: '🗜', k: 'clamp tool' },
  { e: '💽', k: 'computer disk minidisc' },
  { e: '💾', k: 'floppy disk save' },
  { e: '💿', k: 'optical disk cd' },
  { e: '📀', k: 'dvd disc' },
  { e: '📼', k: 'videocassette vhs tape' },
  { e: '📷', k: 'camera photo' },
  { e: '📸', k: 'camera with flash photo' },
  { e: '📹', k: 'video camera' },
  { e: '🎥', k: 'movie camera film' },
  { e: '📽', k: 'film projector movie' },
  { e: '🎞', k: 'film frames' },
  { e: '📞', k: 'telephone receiver call' },
  { e: '☎', k: 'telephone phone' },
  { e: '📟', k: 'pager beeper' },
  { e: '📠', k: 'fax machine' },
  { e: '📺', k: 'television tv' },
  { e: '📻', k: 'radio music' },
  { e: '🎙', k: 'studio microphone' },
  { e: '🎚', k: 'level slider' },
  { e: '🎛', k: 'control knobs mixer' },
  { e: '🧭', k: 'compass navigation' },
  { e: '⏱', k: 'stopwatch timer' },
  { e: '⏲', k: 'timer clock' },
  { e: '⏰', k: 'alarm clock' },
  { e: '🕰', k: 'mantelpiece clock' },
  { e: '⌛', k: 'hourglass done' },
  { e: '⏳', k: 'hourglass not done' },
  { e: '📡', k: 'satellite antenna' },
  { e: '🔋', k: 'battery power' },
  { e: '🪫', k: 'low battery' },
  { e: '🔌', k: 'electric plug' },
  { e: '💡', k: 'light bulb idea' },
  { e: '🔦', k: 'flashlight torch' },
  { e: '🕯', k: 'candle light' },
  { e: '🪔', k: 'diya oil lamp' },
  { e: '🧯', k: 'fire extinguisher' },
  { e: '🛢', k: 'oil drum barrel' },
  { e: '💸', k: 'money with wings spend' },
  { e: '💵', k: 'dollar banknote money' },
  { e: '💴', k: 'yen banknote japan' },
  { e: '💶', k: 'euro banknote' },
  { e: '💷', k: 'pound banknote uk' },
  { e: '🪙', k: 'coin money' },
  { e: '💰', k: 'money bag cash' },
  { e: '💳', k: 'credit card payment' },
  { e: '💎', k: 'gem diamond jewel' },
  { e: '⚖', k: 'balance scale justice' },
  { e: '🪜', k: 'ladder climb' },
  { e: '🧰', k: 'toolbox tools' },
  { e: '🪛', k: 'screwdriver tool' },
  { e: '🔧', k: 'wrench tool' },
  { e: '🔨', k: 'hammer tool' },
  { e: '⚒', k: 'hammer and pick tool' },
  { e: '🛠', k: 'hammer and wrench' },
  { e: '⛏', k: 'pick tool' },
  { e: '🪚', k: 'carpentry saw tool' },
  { e: '🔩', k: 'nut and bolt' },
  { e: '⚙', k: 'gear settings' },
  { e: '🪤', k: 'mouse trap' },
  { e: '🧱', k: 'brick construction' },
  { e: '⛓', k: 'chains link' },
  { e: '🧲', k: 'magnet attraction' },
  { e: '🔫', k: 'water pistol gun' },
  { e: '💣', k: 'bomb explosion' },
  { e: '🧨', k: 'firecracker explosive' },
  { e: '🪓', k: 'axe tool' },
  { e: '🔪', k: 'kitchen knife' },
  { e: '🗡', k: 'dagger weapon' },
  { e: '⚔', k: 'crossed swords' },
  { e: '🛡', k: 'shield protect' },
  { e: '🚬', k: 'cigarette smoke' },
  { e: '⚰', k: 'coffin death' },
  { e: '🪦', k: 'headstone grave' },
  { e: '⚱', k: 'funeral urn' },
  { e: '🏺', k: 'amphora vase' },
  { e: '🔮', k: 'crystal ball magic' },
  { e: '📿', k: 'prayer beads' },
  { e: '🧿', k: 'nazar amulet evil eye' },
  { e: '💈', k: 'barber pole' },
  { e: '⚗', k: 'alembic science' },
  { e: '🔭', k: 'telescope astronomy' },
  { e: '🔬', k: 'microscope science' },
  { e: '🕳', k: 'hole' },
  { e: '💊', k: 'pill medicine' },
  { e: '💉', k: 'syringe injection' },
  { e: '🧬', k: 'dna genetics' },
  { e: '🦠', k: 'microbe virus germ' },
  { e: '🧫', k: 'petri dish lab' },
  { e: '🧪', k: 'test tube science lab' },
  { e: '🌡', k: 'thermometer temperature' },
  { e: '🧹', k: 'broom sweep' },
  { e: '🪠', k: 'plunger plumbing' },
  { e: '🧺', k: 'basket laundry' },
  { e: '🧻', k: 'roll of paper toilet' },
  { e: '🚽', k: 'toilet bathroom' },
  { e: '🚰', k: 'potable water tap' },
  { e: '🚿', k: 'shower bathroom' },
  { e: '🛁', k: 'bathtub bath' },
  { e: '🛀', k: 'person taking bath' },
  { e: '🧼', k: 'soap clean' },
  { e: '🪥', k: 'toothbrush dental' },
  { e: '🪒', k: 'razor shave' },
  { e: '🧽', k: 'sponge clean' },
  { e: '🪣', k: 'bucket pail' },
  { e: '🧴', k: 'lotion bottle' },
  { e: '🛎', k: 'bellhop bell hotel' },
  { e: '🔑', k: 'key unlock' },
  { e: '🗝', k: 'old key' },
  { e: '🚪', k: 'door exit' },
  { e: '🪑', k: 'chair seat' },
  { e: '🛋', k: 'couch sofa' },
  { e: '🛏', k: 'bed sleep' },
  { e: '🛌', k: 'person in bed sleep' },
  { e: '🧸', k: 'teddy bear toy' },
  { e: '🪆', k: 'nesting dolls matryoshka' },
  { e: '🖼', k: 'framed picture art' },
  { e: '🪞', k: 'mirror reflection' },
  { e: '🪟', k: 'window view' },
  { e: '🛍', k: 'shopping bags' },
  { e: '🛒', k: 'shopping cart' },
  { e: '🎁', k: 'wrapped gift present' },
  { e: '🎈', k: 'balloon party' },
  { e: '🎏', k: 'carp streamer koinobori' },
  { e: '🎀', k: 'ribbon bow' },
  { e: '🪄', k: 'magic wand' },
  { e: '🪅', k: 'pinata party' },
  { e: '🎊', k: 'confetti ball party' },
  { e: '🎉', k: 'party popper celebration' },
  { e: '🪩', k: 'mirror ball disco' },
  { e: '🎎', k: 'japanese dolls' },
  { e: '🏮', k: 'red lantern' },
  { e: '🎐', k: 'wind chime' },
  { e: '🧧', k: 'red envelope money gift' },
  { e: '✉', k: 'envelope mail letter' },
  { e: '📩', k: 'envelope arrow incoming' },
  { e: '📨', k: 'incoming envelope mail' },
  { e: '📧', k: 'email e-mail' },
  { e: '💌', k: 'love letter heart' },
  { e: '📥', k: 'inbox tray' },
  { e: '📤', k: 'outbox tray' },
  { e: '📦', k: 'package parcel box' },
  { e: '🏷', k: 'label tag' },
  { e: '🪧', k: 'placard sign' },
  { e: '📪', k: 'closed mailbox lowered' },
  { e: '📫', k: 'closed mailbox raised' },
  { e: '📬', k: 'open mailbox raised' },
  { e: '📭', k: 'open mailbox lowered' },
  { e: '📮', k: 'postbox mail' },
  { e: '📯', k: 'postal horn' },
  { e: '📜', k: 'scroll document' },
  { e: '📃', k: 'page with curl' },
  { e: '📄', k: 'page facing up document' },
  { e: '📑', k: 'bookmark tabs' },
  { e: '🧾', k: 'receipt bill' },
  { e: '📊', k: 'bar chart stats' },
  { e: '📈', k: 'chart increasing growth' },
  { e: '📉', k: 'chart decreasing' },
  { e: '🗒', k: 'spiral notepad' },
  { e: '🗓', k: 'spiral calendar' },
  { e: '📆', k: 'tear off calendar' },
  { e: '📅', k: 'calendar date' },
  { e: '🗑', k: 'wastebasket trash delete' },
  { e: '📇', k: 'card index contacts' },
  { e: '🗃', k: 'card file box' },
  { e: '🗳', k: 'ballot box vote' },
  { e: '🗄', k: 'file cabinet' },
  { e: '📋', k: 'clipboard notes' },
  { e: '📁', k: 'file folder documents' },
  { e: '📂', k: 'open folder' },
  { e: '🗂', k: 'card index dividers' },
  { e: '🗞', k: 'rolled up newspaper' },
  { e: '📰', k: 'newspaper news' },
  { e: '📓', k: 'notebook journal' },
  { e: '📔', k: 'notebook with decorative cover' },
  { e: '📒', k: 'ledger notebook' },
  { e: '📕', k: 'closed book red' },
  { e: '📗', k: 'green book' },
  { e: '📘', k: 'blue book' },
  { e: '📙', k: 'orange book' },
  { e: '📚', k: 'books library' },
  { e: '📖', k: 'open book read' },
  { e: '🔖', k: 'bookmark' },
  { e: '🧷', k: 'safety pin' },
  { e: '🔗', k: 'link chain url' },
  { e: '📎', k: 'paperclip' },
  { e: '🖇', k: 'linked paperclips' },
  { e: '📐', k: 'triangular ruler' },
  { e: '📏', k: 'straight ruler' },
  { e: '🧮', k: 'abacus math' },
  { e: '📌', k: 'pushpin location' },
  { e: '📍', k: 'round pushpin location' },
  { e: '✂', k: 'scissors cut' },
  { e: '🖊', k: 'pen writing' },
  { e: '🖋', k: 'fountain pen' },
  { e: '✒', k: 'black nib pen' },
  { e: '🖌', k: 'paintbrush art' },
  { e: '🖍', k: 'crayon draw' },
  { e: '📝', k: 'memo note' },
  { e: '✏', k: 'pencil write' },
  { e: '🔍', k: 'magnifying glass tilted left search' },
  { e: '🔎', k: 'magnifying glass tilted right search' },
  { e: '🔏', k: 'locked with pen secret' },
  { e: '🔐', k: 'locked with key secure' },
  { e: '🔒', k: 'locked padlock secure' },
  { e: '🔓', k: 'unlocked open' },
  { e: '❤', k: 'red heart love' },
  { e: '🧡', k: 'orange heart love' },
  { e: '💛', k: 'yellow heart love' },
  { e: '💚', k: 'green heart love' },
  { e: '💙', k: 'blue heart love' },
  { e: '💜', k: 'purple heart love' },
  { e: '🖤', k: 'black heart love' },
  { e: '🤍', k: 'white heart love' },
  { e: '🤎', k: 'brown heart love' },
  { e: '💔', k: 'broken heart sad love' },
  { e: '❣', k: 'heart exclamation love' },
  { e: '💕', k: 'two hearts love' },
  { e: '💞', k: 'revolving hearts love' },
  { e: '💓', k: 'beating heart pulse' },
  { e: '💗', k: 'growing heart' },
  { e: '💖', k: 'sparkling heart shine' },
  { e: '💘', k: 'heart with arrow love' },
  { e: '💝', k: 'heart with ribbon gift' },
  { e: '💟', k: 'heart decoration' },
  { e: '♥', k: 'heart suit card' },
  { e: '💌', k: 'love letter' },
  { e: '💯', k: 'hundred points 100' },
  { e: '💢', k: 'anger symbol mad' },
  { e: '💥', k: 'collision boom explosion' },
  { e: '💫', k: 'dizzy symbol star' },
  { e: '💦', k: 'sweat droplets' },
  { e: '💨', k: 'dashing away wind' },
  { e: '💬', k: 'speech balloon chat message' },
  { e: '👁‍🗨', k: 'eye in speech bubble witness' },
  { e: '🗨', k: 'left speech bubble chat' },
  { e: '🗯', k: 'right anger bubble' },
  { e: '💭', k: 'thought balloon think idea' },
  { e: '💤', k: 'zzz sleep' },
  { e: '🌐', k: 'globe internet world' },
  { e: '♠', k: 'spade suit card' },
  { e: '♣', k: 'club suit card' },
  { e: '♥', k: 'heart suit card' },
  { e: '♦', k: 'diamond suit card' },
  { e: '🔷', k: 'large blue diamond' },
  { e: '🔶', k: 'large orange diamond' },
  { e: '🔴', k: 'red circle' },
  { e: '🟠', k: 'orange circle' },
  { e: '🟡', k: 'yellow circle' },
  { e: '🟢', k: 'green circle' },
  { e: '🔵', k: 'blue circle' },
  { e: '🟣', k: 'purple circle' },
  { e: '🟤', k: 'brown circle' },
  { e: '⚫', k: 'black circle' },
  { e: '⚪', k: 'white circle' },
  { e: '🟥', k: 'red square' },
  { e: '🟧', k: 'orange square' },
  { e: '🟨', k: 'yellow square' },
  { e: '🟩', k: 'green square' },
  { e: '🟦', k: 'blue square' },
  { e: '🟪', k: 'purple square' },
  { e: '🟫', k: 'brown square' },
  { e: '🔺', k: 'red triangle up' },
  { e: '🔻', k: 'red triangle down' },
  { e: '🔸', k: 'small orange diamond' },
  { e: '🔹', k: 'small blue diamond' },
  { e: '🔔', k: 'bell notification alert' },
  { e: '🔕', k: 'bell with slash muted' },
  { e: '🎵', k: 'musical note music' },
  { e: '🎶', k: 'musical notes music' },
  { e: '🏳', k: 'white flag' },
  { e: '🏴', k: 'black flag' },
  { e: '🏁', k: 'chequered flag race finish' },
  { e: '🚩', k: 'triangular flag' },
  { e: '🏳️‍🌈', k: 'rainbow flag pride' },
  { e: '🏳️‍⚧️', k: 'transgender flag' },
  { e: '🇧🇩', k: 'bangladesh flag' },
  { e: '🇮🇳', k: 'india flag' },
  { e: '🇺🇸', k: 'united states america flag' },
  { e: '🇬🇧', k: 'united kingdom england flag' },
  { e: '🇨🇳', k: 'china flag' },
  { e: '🇯🇵', k: 'japan flag' },
  { e: '🇰🇷', k: 'korea flag' },
  { e: '🇩🇪', k: 'germany flag' },
  { e: '🇫🇷', k: 'france flag' },
  { e: '🇸🇦', k: 'saudi arabia flag' },
  { e: '🇦🇪', k: 'united arab emirates flag' },
  { e: '🇧🇷', k: 'brazil flag' },
  { e: '🇪🇬', k: 'egypt flag' },
  { e: '🇵🇰', k: 'pakistan flag' },
  { e: '🇳🇵', k: 'nepal flag' },
  { e: '🇱🇰', k: 'sri lanka flag' },
];

export default function EmojiPicker({ onSelect, onClose }) {
  const [query, setQuery] = useState('');
  const [recent, setRecent] = useState(() => []);

  const filtered = useMemo(() => {
    const q = query.trim().toLowerCase();
    if (!q) return EMOJI_DATA;
    return EMOJI_DATA.filter(({ e, k }) => k.includes(q) || e === q);
  }, [query]);

  const pick = (item) => {
    setRecent((r) => [item, ...r.filter((x) => x.e !== item.e)].slice(0, 12));
    onSelect(item.e);
    onClose();
  };

  return (
    <div className="absolute bottom-full mb-2 right-0 w-[340px] max-w-[calc(100vw-24px)] max-h-[360px] bg-white rounded-xl shadow-xl border border-gray-200 z-30 flex flex-col overflow-hidden">
      <div className="p-2 border-b border-gray-100 shrink-0">
        <div className="flex items-center gap-2 bg-[#f1f3f4] rounded-full px-3 py-1.5">
          <svg viewBox="0 0 24 24" className="w-4 h-4 text-gray-400" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
            <circle cx="11" cy="11" r="8" />
            <line x1="21" y1="21" x2="16.65" y2="16.65" />
          </svg>
          <input
            value={query}
            onChange={(e) => setQuery(e.target.value)}
            placeholder="Search emoji"
            className="flex-1 bg-transparent outline-none text-sm text-gray-800 placeholder-gray-400"
            autoFocus
          />
          {query && (
            <button type="button" onClick={() => setQuery('')} className="text-gray-400 hover:text-gray-600 text-lg leading-none">
              ×
            </button>
          )}
        </div>
      </div>
      <div className="overflow-y-auto p-2 grid grid-cols-10 gap-0.5 min-h-0">
        {filtered.length === 0 && (
          <div className="col-span-10 text-center text-sm text-gray-400 py-6">No emoji found</div>
        )}
        {filtered.map((item) => (
          <button
            key={item.e}
            type="button"
            onClick={() => pick(item)}
            className="w-8 h-8 rounded-lg hover:bg-gray-100 flex items-center justify-center text-lg transition"
            title={item.k}
          >
            {item.e}
          </button>
        ))}
      </div>
    </div>
  );
}
